#  David Vaughan  R1166390
# (MATH-4000-004)
# Homework 5 02/22/2023
#  Spring 2023 TTU Selected Topics: Machine learning model order reduction for differential equations (MATH-4000-004) Full Term: Homework for week 5/6 (due 02/22)

### Problem 1

Consider the matrix $A$:
$$
A =
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$
and the convolutional layer Conv2d with the property (in_channels=1, out_channels=1, kernel_size=2, stride=1, padding=1) and the kernel $K$
$$
K =
\begin{pmatrix}
0 & 1 \\
1 & 2 
\end{pmatrix}
$$

Compute the output Conv2d(A) using Python code.

In [71]:
import torch
import torch.nn as nn
import numpy as np

In [89]:
#could transpose
#maybe way to use for loop or something to make this?
A =torch.tensor([([[ 0.,1.,2.,3.,4.],
        [ 1.,2.,3.,4.,0.],
        [ 2.,3.,4.,0.,1.],
        [ 3.,4.,0.,1.,2.],
        [ 4.,0.,1.,2.,3.]])])
#w =torch.tensor([[ 0,1],
 #       [ 1,2]])


print("shape",A.shape)
print(A)



shape torch.Size([1, 5, 5])
tensor([[[0., 1., 2., 3., 4.],
         [1., 2., 3., 4., 0.],
         [2., 3., 4., 0., 1.],
         [3., 4., 0., 1., 2.],
         [4., 0., 1., 2., 3.]]])


In [90]:
cnn = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2,stride=1,padding=1)
# weight: of size (out_channels, in_channels, kernel_size[0], kernel_size[1])
# bias: of size (out_channels)
for name, param in cnn.named_parameters():
    if param.requires_grad:
        print(name, ': \n', param.data)
w = cnn.weight
w_np = w.detach().numpy()
w_np[0,0,0,:] = 0.,1.
w_np[0,0,1,:] = 1.,2
#w_np[0,0] = 0,1
#w_np[0,0] = 1,2
cnn.weight = torch.nn.Parameter(torch.from_numpy(w_np))
for name, param in cnn.named_parameters():
    if param.requires_grad:
        print(name, ': \n', param.data) 


weight : 
 tensor([[[[0.1787, 0.4544],
          [0.0884, 0.4732]]]])
bias : 
 tensor([0.3287])
weight : 
 tensor([[[[0., 1.],
          [1., 2.]]]])
bias : 
 tensor([0.3287])


In [91]:
out = cnn(A)
print('output matrix: \n', out)

output matrix: 
 tensor([[[ 0.3287,  2.3287,  5.3287,  8.3287, 11.3287,  4.3287],
         [ 2.3287,  6.3287, 10.3287, 14.3287,  8.3287,  0.3287],
         [ 5.3287, 10.3287, 14.3287,  8.3287,  2.3287,  1.3287],
         [ 8.3287, 14.3287,  8.3287,  2.3287,  6.3287,  2.3287],
         [11.3287,  8.3287,  2.3287,  6.3287, 10.3287,  3.3287],
         [ 4.3287,  0.3287,  1.3287,  2.3287,  3.3287,  0.3287]]],
       grad_fn=<SqueezeBackward1>)


### Problem 2
For the same matrix $A$ in Problem 1, consider the Max Pooling layer MaxPool2d with the property (kernel_size=2, stride=1, padding=1). Compute the output MaxPool2d(A) using Python code.

In [96]:
maxpool2 = nn.MaxPool2d(kernel_size=2, stride=1, padding=1)
out2 = maxpool2(A)
print('A is : \n', A)
print('output image: \n', out2)

A is : 
 tensor([[[0., 1., 2., 3., 4.],
         [1., 2., 3., 4., 0.],
         [2., 3., 4., 0., 1.],
         [3., 4., 0., 1., 2.],
         [4., 0., 1., 2., 3.]]])
output image: 
 tensor([[[0., 1., 2., 3., 4., 4.],
         [1., 2., 3., 4., 4., 4.],
         [2., 3., 4., 4., 4., 1.],
         [3., 4., 4., 4., 2., 2.],
         [4., 4., 4., 2., 3., 3.],
         [4., 4., 1., 2., 3., 3.]]])


### Problem 3
#### (this problem is optional and will not be counted in grade)
For two probability distributions $p=(p_1,p_2,\cdots,p_n)$ and $q=(q_1,q_2,\cdots,q_n)$, the cross entropy is defined as: $$l(p,q) = - \sum_{i=1}^n q_i \log p_i$$
Prove that
$$ l(p,q) \ge l(q,q)$$

# Proveing things is for mathmaticians

Code for me to look at in the future

In [28]:
#could transpose
#maybe way to use for loop or something to make this?
A =torch.tensor([[ 0,1,2,3,4],
        [ 1,2,3,4,0],
        [ 2,3,4,0,1],
        [ 3,4,0,1,2],
        [ 4,0,1,2,3]])
w =torch.tensor([[ 0,1],
        [ 1,2]])
 
print(w)
print(A)

tensor([[0, 1],
        [1, 2]])
tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 0],
        [2, 3, 4, 0, 1],
        [3, 4, 0, 1, 2],
        [4, 0, 1, 2, 3]])


In [29]:
cnn = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2,stride=1,padding=1)
# weight: of size (out_channels, in_channels, kernel_size[0], kernel_size[1])
# bias: of size (out_channels)
for name, param in cnn.named_parameters():
    if param.requires_grad:
        print(name, ': \n', param.data)
w = cnn.weight
w_np = w.detach().numpy()
w_np[0,0,0,:] = 0,1
w_np[0,0,1,:] = 1,2
#w_np[0,0] = 0,1
#w_np[0,0] = 1,2
cnn.weight = torch.nn.Parameter(torch.from_numpy(w_np))
for name, param in cnn.named_parameters():
    if param.requires_grad:
        print(name, ': \n', param.data) 


weight : 
 tensor([[[[-0.2018,  0.1330],
          [ 0.1719,  0.3067]]]])
bias : 
 tensor([0.4281])
weight : 
 tensor([[[[0., 1.],
          [1., 2.]]]])
bias : 
 tensor([0.4281])


In [30]:
out = cnn(A)
print('output matrix: \n', out)

RuntimeError: Input type (__int64) and bias type (float) should be the same