### Problem 1

In [5]:
import torch
import torch.nn as nn
import numpy

A = torch.tensor([[[0,1,2,3,4],[1,2,3,4,0],[2,3,4,0,1],[3,4,0,1,2],[4,0,1,2,3]]]).float()

cnn = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, padding=1, bias=False)

w = cnn.weight

w_np = w.detach().numpy()
w_np[0,0,0] = [0,1]
w_np[0,0,1] = [1,2]

cnn.weight = torch.nn.Parameter(torch.from_numpy(w_np))

for name, param in cnn.named_parameters():
    if param.requires_grad:
        print(name, ': \n', param.data)

out = cnn(A)
print('output image: \n', out)

weight : 
 tensor([[[[0., 1.],
          [1., 2.]]]])
output image: 
 tensor([[[ 0.,  2.,  5.,  8., 11.,  4.],
         [ 2.,  6., 10., 14.,  8.,  0.],
         [ 5., 10., 14.,  8.,  2.,  1.],
         [ 8., 14.,  8.,  2.,  6.,  2.],
         [11.,  8.,  2.,  6., 10.,  3.],
         [ 4.,  0.,  1.,  2.,  3.,  0.]]], grad_fn=<SqueezeBackward1>)


### Problem 2

In [6]:
maxpool = nn.MaxPool2d(2, stride = 1, padding = 1)
out_mp = maxpool(A)
print('output image: \n', out_mp)

output image: 
 tensor([[[0., 1., 2., 3., 4., 4.],
         [1., 2., 3., 4., 4., 4.],
         [2., 3., 4., 4., 4., 1.],
         [3., 4., 4., 4., 2., 2.],
         [4., 4., 4., 2., 3., 3.],
         [4., 4., 1., 2., 3., 3.]]])


### Problem 3

$$
\begin{aligned}
l(p,q) &= - \sum_{i=1}^n q_i \log p_i \\
&= - \sum_{i=1}^n q_i \log \left( \frac{p_i}{q_i} \right) - \sum_{i=1}^n q_i \log q_i \\
&\ge - \sum_{i=1}^n q_i \left( \frac{p_i}{q_i}-1 \right) - \sum_{i=1}^n q_i \log q_i \quad (\textrm{here we use:} \log x\le x - 1)\\
&= - \sum_{i=1}^n p_i + \sum_{i=1}^n q_i - \sum_{i=1}^n q_i \log q_i \\
&= - 1 + 1 - \sum_{i=1}^n q_i \log q_i \\
&= - \sum_{i=1}^n q_i \log q_i \\
&= l(q,q)
\end{aligned}
$$